# Generated by Django 5.2 on 2025-05-10 19:37

import core.validators
import datetime
import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='RecordCategory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name_normalize',
                    models.CharField(
                        auto_created=True,
                        blank=True,
                        help_text='Сгенерированное поле на основе названия',
                        max_length=64,
                        verbose_name='название (нормализованное)',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Максимум 64 символа',
                        max_length=64,
                        verbose_name='название',
                    ),
                ),
            ],
            options={
                'verbose_name': 'record category',
                'verbose_name_plural': 'record categories',
            },
        ),
        migrations.CreateModel(
            name='RecordStatus',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name_normalize',
                    models.CharField(
                        auto_created=True,
                        blank=True,
                        help_text='Сгенерированное поле на основе названия',
                        max_length=64,
                        verbose_name='название (нормализованное)',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Максимум 64 символа',
                        max_length=64,
                        verbose_name='название',
                    ),
                ),
            ],
            options={
                'verbose_name': 'record status',
                'verbose_name_plural': 'record statuses',
            },
        ),
        migrations.CreateModel(
            name='RecordType',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name_normalize',
                    models.CharField(
                        auto_created=True,
                        blank=True,
                        help_text='Сгенерированное поле на основе названия',
                        max_length=64,
                        verbose_name='название (нормализованное)',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Максимум 64 символа',
                        max_length=64,
                        verbose_name='название',
                    ),
                ),
            ],
            options={
                'verbose_name': 'record type',
                'verbose_name_plural': 'record types',
            },
        ),
        migrations.CreateModel(
            name='RecordSubCategory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name_normalize',
                    models.CharField(
                        auto_created=True,
                        blank=True,
                        help_text='Сгенерированное поле на основе названия',
                        max_length=64,
                        verbose_name='название (нормализованное)',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Максимум 64 символа',
                        max_length=64,
                        verbose_name='название',
                    ),
                ),
                (
                    'categories',
                    models.ManyToManyField(
                        related_name='sub_categories',
                        related_query_name='sub_categories',
                        to='catalog.recordcategory',
                        verbose_name='sub category',
                    ),
                ),
            ],
            options={
                'verbose_name': 'record sub category',
                'verbose_name_plural': 'record sub categories',
            },
        ),
        migrations.AddField(
            model_name='recordcategory',
            name='record_types',
            field=models.ManyToManyField(
                related_name='categories',
                related_query_name='categories',
                to='catalog.recordtype',
                verbose_name='type',
            ),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'comment',
                    models.TextField(
                        blank=True,
                        help_text='Max length is 65535',
                        max_length=65535,
                        null=True,
                        verbose_name='comment',
                    ),
                ),
                (
                    'created_at',
                    models.DateField(
                        default=datetime.date.today,
                        validators=[core.validators.validate_date_future],
                        verbose_name='creation date',
                    ),
                ),
                (
                    'total',
                    models.PositiveIntegerField(
                        help_text='Enter positive number',
                        verbose_name='total (rub.)',
                    ),
                ),
                (
                    'category',
                    smart_selects.db_fields.ChainedForeignKey(
                        chained_field='record_type',
                        chained_model_field='record_types',
                        help_text='Select "Type" at first.',
                        on_delete=django.db.models.deletion.RESTRICT,
                        to='catalog.recordcategory',
                        verbose_name='category',
                    ),
                ),
                (
                    'status',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='catalog.recordstatus',
                        verbose_name='status',
                    ),
                ),
                (
                    'sub_category',
                    smart_selects.db_fields.ChainedForeignKey(
                        chained_field='category',
                        chained_model_field='categories',
                        help_text='Select "Category" at first.',
                        on_delete=django.db.models.deletion.RESTRICT,
                        to='catalog.recordsubcategory',
                        verbose_name='sub category',
                    ),
                ),
                (
                    'record_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to='catalog.recordtype',
                        verbose_name='type',
                    ),
                ),
            ],
            options={
                'verbose_name': 'cash flow record',
                'verbose_name_plural': 'cash flow records',
                'default_related_name': 'records',
            },
        ),
    ]
